export const businessCategories = [
  "Gaming",
  "B2B",
  "Digital goods",
  "Ecommerce",
  "Education",
  "Proprietorship",
  "Financial Services",
  "Government",
  "Grocery",
  "Health Care",
  "Insurance",
  "Jewellery",
  "Logistics",
  "Mutual Funds",
  "NBFC",
  "Non Profit",
  "Online Gaming",
  "Open and semi-open wallet",
  "Pharmacy",
  "Retail and Shopping",
  "SaaS",
  "Telecom",
  "Travel and Hospitality",
  "Utilities",
];

export const states = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu & Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttarakhand",
  "Uttar Pradesh",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Delhi",
  "Dadra and Nagar Haveli",
  "Daman and Diu",
  "Lakshadweep",
  "Puducherry",
  "Ladakh",
];
